language: R
sudo: false
cache: packages
warnings_are_errors: false
r_packages:
- covr
after_success:
- Rscript -e 'covr::codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "dev" && bash readme_updater.sh
before_install:
- openssl aes-256-cbc -K $encrypted_92e990fc8647_key -iv $encrypted_92e990fc8647_iv
  -in deploy_rsa.enc -out deploy_rsa -d
